import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.employee.deleteMany();

  await prisma.employee.createMany({
    data: [
      {
        name: "Lukasz",
        surname: "Malinowski",
        position: "Frontend Developer",
        project: "Acme Portal",
        hourlyRate: 82,
        hoursWorked: 96,
        status: "active",
      },
      {
        name: "Katarzyna",
        surname: "Nowicka",
        position: "Backend Developer",
        project: "Acme Portal",
        hourlyRate: 94,
        hoursWorked: 130,
        status: "active",
      },
      {
        name: "Pawel",
        surname: "Dabrowski",
        position: "QA Engineer",
        project: "Acme Portal",
        hourlyRate: 68,
        hoursWorked: 88,
        status: "inactive",
      },
      {
        name: "Alicja",
        surname: "Sikora",
        position: "DevOps Engineer",
        project: "Acme Portal",
        hourlyRate: 101,
        hoursWorked: 72,
        status: "active",
      },
      {
        name: "Marek",
        surname: "Czarnecki",
        position: "Project Manager",
        project: "Acme Portal",
        hourlyRate: 89,
        hoursWorked: 110,
        status: "on_leave",
      },
      {
        name: "Natalia",
        surname: "Jankowska",
        position: "Frontend Developer",
        project: "Beta Mobile",
        hourlyRate: 79,
        hoursWorked: 104,
        status: "active",
      },
      {
        name: "Sebastian",
        surname: "Kaczmarek",
        position: "Backend Developer",
        project: "Beta Mobile",
        hourlyRate: 96,
        hoursWorked: 122,
        status: "active",
      },
      {
        name: "Karolina",
        surname: "Wasilewska",
        position: "QA Engineer",
        project: "Beta Mobile",
        hourlyRate: 71,
        hoursWorked: 90,
        status: "inactive",
      },
      {
        name: "Tomasz",
        surname: "Majewski",
        position: "DevOps Engineer",
        project: "Beta Mobile",
        hourlyRate: 99,
        hoursWorked: 66,
        status: "active",
      },
      {
        name: "Monika",
        surname: "Adamska",
        position: "Business Analyst",
        project: "Beta Mobile",
        hourlyRate: 74,
        hoursWorked: 98,
        status: "active",
      },
      {
        name: "Damian",
        surname: "Walczak",
        position: "Data Engineer",
        project: "Gamma Analytics",
        hourlyRate: 93,
        hoursWorked: 136,
        status: "active",
      },
      {
        name: "Izabela",
        surname: "Szymanska",
        position: "Data Analyst",
        project: "Gamma Analytics",
        hourlyRate: 77,
        hoursWorked: 118,
        status: "active",
      },
      {
        name: "Rafal",
        surname: "Lis",
        position: "Backend Developer",
        project: "Gamma Analytics",
        hourlyRate: 91,
        hoursWorked: 126,
        status: "inactive",
      },
      {
        name: "Paulina",
        surname: "Pawlak",
        position: "QA Engineer",
        project: "Gamma Analytics",
        hourlyRate: 69,
        hoursWorked: 84,
        status: "on_leave",
      },
      {
        name: "Michal",
        surname: "Baran",
        position: "Project Manager",
        project: "Gamma Analytics",
        hourlyRate: 88,
        hoursWorked: 108,
        status: "active",
      },
      {
        name: "Jakub",
        surname: "Wrobel",
        position: "Frontend Developer",
        project: "Delta CRM",
        hourlyRate: 81,
        hoursWorked: 92,
        status: "active",
      },
      {
        name: "Aleksandra",
        surname: "Rutkowska",
        position: "Backend Developer",
        project: "Delta CRM",
        hourlyRate: 95,
        hoursWorked: 124,
        status: "active",
      },
      {
        name: "Bartosz",
        surname: "Kubiak",
        position: "QA Engineer",
        project: "Delta CRM",
        hourlyRate: 67,
        hoursWorked: 86,
        status: "inactive",
      },
      {
        name: "Emilia",
        surname: "Michalik",
        position: "UX Designer",
        project: "Delta CRM",
        hourlyRate: 76,
        hoursWorked: 94,
        status: "active",
      },
      {
        name: "Adrian",
        surname: "Gorski",
        position: "DevOps Engineer",
        project: "Delta CRM",
        hourlyRate: 100,
        hoursWorked: 70,
        status: "active",
      },
      {
        name: "Joanna",
        surname: "Sadowska",
        position: "Frontend Developer",
        project: "Echo Billing",
        hourlyRate: 80,
        hoursWorked: 102,
        status: "active",
      },
      {
        name: "Patryk",
        surname: "Grabowski",
        position: "Backend Developer",
        project: "Echo Billing",
        hourlyRate: 97,
        hoursWorked: 128,
        status: "on_leave",
      },
      {
        name: "Weronika",
        surname: "Kowalczyk",
        position: "QA Engineer",
        project: "Echo Billing",
        hourlyRate: 70,
        hoursWorked: 82,
        status: "active",
      },
      {
        name: "Hubert",
        surname: "Mazurek",
        position: "Business Analyst",
        project: "Echo Billing",
        hourlyRate: 75,
        hoursWorked: 100,
        status: "active",
      },
      {
        name: "Magdalena",
        surname: "Piasecka",
        position: "Project Manager",
        project: "Echo Billing",
        hourlyRate: 90,
        hoursWorked: 112,
        status: "inactive",
      },
      {
        name: "Szymon",
        surname: "Witkowski",
        position: "Data Engineer",
        project: "Acme Portal",
        hourlyRate: 92,
        hoursWorked: 132,
        status: "active",
      },
      {
        name: "Agata",
        surname: "Duda",
        position: "UX Designer",
        project: "Beta Mobile",
        hourlyRate: 73,
        hoursWorked: 96,
        status: "active",
      },
      {
        name: "Marcin",
        surname: "Krol",
        position: "Security Engineer",
        project: "Gamma Analytics",
        hourlyRate: 104,
        hoursWorked: 64,
        status: "active",
      },
      {
        name: "Julia",
        surname: "Kurek",
        position: "Frontend Developer",
        project: "Delta CRM",
        hourlyRate: 78,
        hoursWorked: 106,
        status: "active",
      },
      {
        name: "Oskar",
        surname: "Borkowski",
        position: "Backend Developer",
        project: "Echo Billing",
        hourlyRate: 98,
        hoursWorked: 134,
        status: "active",
      },
      {
        name: "Zuzanna",
        surname: "Urban",
        position: "QA Engineer",
        project: "Acme Portal",
        hourlyRate: 72,
        hoursWorked: 80,
        status: "inactive",
      },
      {
        name: "Kamil",
        surname: "Pietrzak",
        position: "DevOps Engineer",
        project: "Beta Mobile",
        hourlyRate: 102,
        hoursWorked: 68,
        status: "active",
      },
      {
        name: "Anna",
        surname: "Kucharska",
        position: "Business Analyst",
        project: "Gamma Analytics",
        hourlyRate: 76,
        hoursWorked: 104,
        status: "active",
      },
      {
        name: "Filip",
        surname: "Jablonski",
        position: "Project Manager",
        project: "Delta CRM",
        hourlyRate: 91,
        hoursWorked: 114,
        status: "on_leave",
      },
      {
        name: "Marta",
        surname: "Kania",
        position: "Data Analyst",
        project: "Echo Billing",
        hourlyRate: 74,
        hoursWorked: 92,
        status: "active",
      },
      {
        name: "Przemyslaw",
        surname: "Stepien",
        position: "Frontend Developer",
        project: "Acme Portal",
        hourlyRate: 83,
        hoursWorked: 98,
        status: "active",
      },
      {
        name: "Sylwia",
        surname: "Wrona",
        position: "Backend Developer",
        project: "Beta Mobile",
        hourlyRate: 93,
        hoursWorked: 120,
        status: "inactive",
      },
      {
        name: "Dawid",
        surname: "Sroka",
        position: "QA Engineer",
        project: "Gamma Analytics",
        hourlyRate: 68,
        hoursWorked: 88,
        status: "active",
      },
      {
        name: "Ewelina",
        surname: "Tomczak",
        position: "UX Designer",
        project: "Delta CRM",
        hourlyRate: 77,
        hoursWorked: 100,
        status: "active",
      },
      {
        name: "Grzegorz",
        surname: "Zawadzki",
        position: "Security Engineer",
        project: "Echo Billing",
        hourlyRate: 106,
        hoursWorked: 62,
        status: "active",
      },
    ],
  });

  console.log("Seeded 40 employees");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });